app = "route-snap-frontend"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[env]
  BACKEND_API_BASE_URL = "https://route-snap-backend.fly.dev"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
